/**
 * Strips non-DOM props from a props object, returning only valid HTML/React DOM attributes.
 * Uses an allowlist approach: only known-valid DOM attributes pass through.
 * This allows migrated components to remain backward-compatible with consumers
 * that still pass Panda-style props (e.g. `bg`, `w`, `boxSize`, `_hover`).
 */
const VALID_DOM_PROPS = new Set([
  // React-specific
  "children",
  "dangerouslySetInnerHTML",
  "key",
  "ref",
  "suppressContentEditableWarning",
  "suppressHydrationWarning",
  // Global HTML attributes
  "accessKey",
  "autoCapitalize",
  "autoFocus",
  "className",
  "contentEditable",
  "dir",
  "draggable",
  "enterKeyHint",
  "hidden",
  "id",
  "inputMode",
  "is",
  "itemID",
  "itemProp",
  "itemRef",
  "itemScope",
  "itemType",
  "lang",
  "nonce",
  "placeholder",
  "slot",
  "spellCheck",
  "style",
  "tabIndex",
  "title",
  "translate",
  "popover",
  "popoverTarget",
  "popoverTargetAction",
  // Accessibility / ARIA (handled dynamically below)
  "role",
  // Form attributes
  "accept",
  "acceptCharset",
  "action",
  "allowFullScreen",
  "alt",
  "async",
  "autoComplete",
  "autoPlay",
  "capture",
  "cellPadding",
  "cellSpacing",
  "challenge",
  "charSet",
  "checked",
  "cite",
  "classID",
  "cols",
  "colSpan",
  "content",
  "controls",
  "coords",
  "crossOrigin",
  "data",
  "dateTime",
  "default",
  "defer",
  "disabled",
  "download",
  "encType",
  "form",
  "formAction",
  "formEncType",
  "formMethod",
  "formNoValidate",
  "formTarget",
  "frameBorder",
  "headers",
  "height",
  "high",
  "href",
  "hrefLang",
  "htmlFor",
  "httpEquiv",
  "icon",
  "integrity",
  "keyParams",
  "keyType",
  "kind",
  "label",
  "list",
  "loop",
  "low",
  "manifest",
  "marginHeight",
  "marginWidth",
  "max",
  "maxLength",
  "media",
  "mediaGroup",
  "method",
  "min",
  "minLength",
  "multiple",
  "muted",
  "name",
  "noValidate",
  "open",
  "optimum",
  "pattern",
  "playsInline",
  "poster",
  "preload",
  "profile",
  "radioGroup",
  "readOnly",
  "rel",
  "required",
  "reversed",
  "rows",
  "rowSpan",
  "sandbox",
  "scope",
  "scoped",
  "scrolling",
  "seamless",
  "selected",
  "shape",
  "size",
  "sizes",
  "span",
  "src",
  "srcDoc",
  "srcLang",
  "srcSet",
  "start",
  "step",
  "summary",
  "target",
  "type",
  "useMap",
  "value",
  "width",
  "wmode",
  "wrap",
  // Media events
  "onAbort",
  "onCanPlay",
  "onCanPlayThrough",
  "onDurationChange",
  "onEmptied",
  "onEncrypted",
  "onEnded",
  "onError",
  "onLoadedData",
  "onLoadedMetadata",
  "onLoadStart",
  "onPause",
  "onPlay",
  "onPlaying",
  "onProgress",
  "onRateChange",
  "onSeeked",
  "onSeeking",
  "onStalled",
  "onSuspend",
  "onTimeUpdate",
  "onVolumeChange",
  "onWaiting",
  // Clipboard events
  "onCopy",
  "onCut",
  "onPaste",
  // Composition events
  "onCompositionEnd",
  "onCompositionStart",
  "onCompositionUpdate",
  // Focus events
  "onFocus",
  "onBlur",
  // Form events
  "onChange",
  "onInput",
  "onInvalid",
  "onReset",
  "onSubmit",
  // Image events
  "onLoad",
  // Keyboard events
  "onKeyDown",
  "onKeyPress",
  "onKeyUp",
  // Mouse events
  "onClick",
  "onContextMenu",
  "onDoubleClick",
  "onDrag",
  "onDragEnd",
  "onDragEnter",
  "onDragExit",
  "onDragLeave",
  "onDragOver",
  "onDragStart",
  "onDrop",
  "onMouseDown",
  "onMouseEnter",
  "onMouseLeave",
  "onMouseMove",
  "onMouseOut",
  "onMouseOver",
  "onMouseUp",
  // Pointer events
  "onPointerDown",
  "onPointerMove",
  "onPointerUp",
  "onPointerCancel",
  "onGotPointerCapture",
  "onLostPointerCapture",
  "onPointerEnter",
  "onPointerLeave",
  "onPointerOver",
  "onPointerOut",
  // Selection events
  "onSelect",
  // Touch events
  "onTouchCancel",
  "onTouchEnd",
  "onTouchMove",
  "onTouchStart",
  // UI events
  "onScroll",
  // Wheel events
  "onWheel",
  // Animation events
  "onAnimationStart",
  "onAnimationEnd",
  "onAnimationIteration",
  // Transition events
  "onTransitionEnd",
]);

function isValidDomProp(key: string): boolean {
  if (VALID_DOM_PROPS.has(key)) return true;
  if (key.startsWith("data-") || key.startsWith("aria-")) return true;
  return false;
}

export function filterDomProps<T extends Record<string, any>>(
  props: T,
): T {
  const filtered: Record<string, any> = {};
  for (const key in props) {
    if (isValidDomProp(key)) {
      filtered[key] = props[key];
    }
  }
  return filtered as T;
}
